### ISSUE TITLE
ServiceEntry doesn't work in Kmesh

### ISSUE THREAD

**Issue by YaoZengzeng** [kmesh-net/kmesh#1037]
**What happened**:

I deployed a ServiceEntry like this :
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-se-v4
spec:
  hosts:
  - dummy-v4.example.com
  addresses:
  - 240.240.240.255
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  # Expose bookinfo through gateway first.
  - address: 172.18.0.0
    ports:
      http: 80
```

`172.18.0.0` is the external IP of ingress gateway and I expose `bookinfo` in port `80`, but it doesn't work as expected.

```bash
kubectl exec deploy/sleep -- curl -v http://240.240.240.255:80/productpage
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 240.240.240.255:80...
  0     0    0     0    0     0      0      0 --:--:--  0:00:26 --:--:--     0
```

**What you expected to happen**:

Should be able to access.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:
