### ISSUE TITLE
Kmesh should support port name mapping in ServiceEntry

### ISSUE THREAD

**Issue by YaoZengzeng** [kmesh-net/kmesh#1088]
**What would you like to be added**:

```yaml 
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-se-v4
spec:
  hosts:
  - dummy-v4.example.com
  addresses:
  - 240.240.240.255
  ports:
  - number: 80
    name: http
    protocol: HTTP
  endpoints:
  - address: 172.18.0.3
    ports:
      http: 8080
```

According to the spec, in ServiceEntry, if the key of the ports in the inline WorkloadEntry matches the name of the port in ServiceEntry, the port is used as the port to access the backend, regardless of whether the target port is specified.

However, it doesn't work in Kmesh.

**Why is this needed**:

Official spec requirements
