### ISSUE TITLE
kmeshctl waypoint generate wrong proxyImage tag

### ISSUE THREAD

**Issue by silenceper** [kmesh-net/kmesh#1287]
**What happened**:

```
kmeshctl waypoint generate -n default

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    sidecar.istio.io/proxyImage: ghcr.io/kmesh-net/waypoint:vv1.0.0 
  name: waypoint
  namespace: default
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
```

**What you expected to happen**:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    sidecar.istio.io/proxyImage: ghcr.io/kmesh-net/waypoint:v1.0.0
  name: waypoint
  namespace: default
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
client version: v1.0.0-44069d88ffd77e8be3aa81f890fd37f0f02a51f7

- Kmesh version: 
- Kmesh mode(kmesh has `Kernel-Native Mode` and `Duel-Engine Mode`):
- Istio version:
- Kernel version:
- Others:
