### ISSUE TITLE
There is a problem with setting Authorization for workloads in waypoint managed.

### ISSUE THREAD

**Issue by LiZhenCheng9527** [kmesh-net/kmesh#1394]
**What happened**:
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-by-srcip
  namespace: default
spec:
  selector:
    matchLabels:
      app: httpbin
  action: ALLOW
  rules:
  - from:
    - source:
        ipBlocks:
        - 10.244.1.46/32
```

When httpbin is managed by waypoint, even `10.244.1.46` access to httpbin is denied.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kmesh version:
- Kmesh mode(kmesh has `Kernel-Native Mode` and `Duel-Engine Mode`):
- Istio version:
- Kernel version:
- Others:
