### ISSUE TITLE
Dead loop for data synchronization between istio and kmesh

### ISSUE THREAD

**Issue by PerforMance308** [kmesh-net/kmesh#189]
**What happened**:
- Istio dispatches configurations to kmesh dead loop
- Modification of deployed services and their routing policies in the environment is slow to take effect, more than 3 minutes. Even if restart Kmesh.

**What you expected to happen**:
- configuration changes should be taken into effect in very short time

**How to reproduce it (as minimally and precisely as possible)**:
Deploy 3 services:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: httpecho-a
  labels:
    app: httpecho-a
    service: httpecho-a
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: httpecho-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpecho-a
  labels:
    app: httpecho-a
spec:
  selector:
    matchLabels:
      app: httpecho-a
  template:
    metadata:
      labels:
        app: httpecho-a
    spec:
      containers:
      - name: httpecho-a
        image: docker.io/istio/examples-helloworld-v1
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: httpecho-b
  labels:
    app: httpecho-b
    service: httpecho-b
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: httpecho-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpecho-b
  labels:
    app: httpecho-b
spec:
  selector:
    matchLabels:
      app: httpecho-b
  template:
    metadata:
      labels:
        app: httpecho-b
    spec:
      containers:
      - name: httpecho-b
        image: docker.io/istio/examples-helloworld-v1
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: httpecho-c
  labels:
    app: httpecho-c
    service: httpecho-c
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: httpecho-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpecho-c
  labels:
    app: httpecho-c
spec:
  selector:
    matchLabels:
      app: httpecho-c
  template:
    metadata:
      labels:
        app: httpecho-c
    spec:
      containers:
      - name: httpecho-c
        image: docker.io/istio/examples-helloworld-v1
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
```

Deploy virtualservice： Route requests targeting service b to service c

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: route-directly
spec:
  hosts:
  - httpecho-b.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: httpecho-a.default.svc.cluster.local
```

Randomly remove the above services and redeploy them (multiple times) and modify the virtualservice to point the destination to a different backend service. Could reproduce all the above issues.

- The logs for istiod during the dead loop problem are as follows：

![image](https://github.com/kmesh-net/kmesh/assets/12728232/86023cac-3a33-4d5a-91fc-8a45e8b960c7)

**Anything else we need to know?**:

**Environment**:
- OS: Ubuntu 22.04.3
- Kmesh version: latest built from main branch
- istio version: 1.19
