### ISSUE TITLE
Kmesh does not handle request unless return value of check_sock_enable_kmesh is hardcoded to True

### ISSUE THREAD

**Issue by tmodak27** [kmesh-net/kmesh#210]
If we deploy Kmesh using a locally built image, Kmesh does not handle any requests. In order for Kmesh to handle requests we need to hardcode the return value of [check_sock_enable to True](https://github.com/kmesh-net/kmesh/blob/main/bpf/kmesh/cgroup_sock.c#L45)

**What you expected to happen**:

We should not need to make this code change for Kmesh to handle the request.

**How to reproduce it (as minimally and precisely as possible)**:

1. Build Kmesh locally.
2. Deploy the below backend service

```
apiVersion: v1
kind: Service
metadata:
  name: app-b
  labels:
    app: app-b
    service: app-b
spec:
  ports:
  - port: 8000
    name: httpb
  selector:
    app: app-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  labels:
    app: app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: app-b
        image: swr.cn-north-4.myhuaweicloud.com/hwstaff_pub_torontodsdelab/fastapi-sample:v1.2
        env:
        - name: SERVICE_NAME
          value: "app-b"
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 8000

```
3. Deploy Kmesh
4. Send Http Request And View BPF Logs

```
kubectl exec -it netutils -- curl app-b:8000/hello
```

The BPF logs show no response, meaning Kmesh does not handel the request.

5. Perform all the above steps and set the return type of `check_sock_enable_kmesh` to True instead of False and send the HTTP request. The bpf logs show that kmesh handles the request.

```
..
21 100591.523186: bpf_trace_printk: [KMESH] DEBUG: bpf find listener addr=[2681824522:16415]

<...>-341703  [002] d..21 100591.523255: bpf_trace_printk: [CLUSTER] INFO: 1 lb_policy is unsupport, defaut:ROUND_ROBIN

<...>-341703  [002] d..21 100591.523260: bpf_trace_printk: [CLUSTER] INFO: cluster="outbound|8000||app-b.default.svc.cluster.local", loadbalance to addr=[3339430080:16415]

```

**Anything else we need to know?**:

* OS: OpenEuler 23.03 and Ubuntu 22.04
* Istio: 1.19
* Kubernetes: 1.27.
* Kmesh version: Latest code from main branch
