### ISSUE TITLE
Kmesh does not handle request sent from Java app

### ISSUE THREAD

**Issue by PerforMance308** [kmesh-net/kmesh#244]
![image](https://github.com/kmesh-net/kmesh/assets/12728232/bbd90e66-2f83-4085-805b-6f96960607c6)

**What happened**:
I have two services: B and C which are written in Java. I use curl to send a http request to B and then B will send a http request to C. 

what I suspect is kmesh could handle request from curl -> B, while kmesh didn't pick up the request sent from B -> C. I tried with different java http libiaries including restTemplate and httpclient, but neither works.

If I send a request directly from curl -> C, Kmesh could handle it

**I tried with same apps that written in Python and Golang and works as expected.**

logs: for B -> C

![image](https://github.com/kmesh-net/kmesh/assets/12728232/4e6916d8-1256-4781-8712-46ee8f2fc1d9)

I'm not sure if this caused by coreDNS. but in service B, I use `app-a.default.svc.cluster.local` as the uri

**What you expected to happen**:
Kmesh could handle request from curl -> B and B -> C.

**How to reproduce it (as minimally and precisely as possible)**:

app-a code:
```java
package org.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.RestTemplate;

@SpringBootApplication
public class ConsumerApplication {
    public static void main(String[] args) {
        SpringApplication.run(ConsumerApplication.class, args);
    }
}

@RestController
class ConsumerController {
    @RequestMapping("/echo")
    public String echo() {
        RestTemplate restTemplate = new RestTemplate();
        ResponseEntity<String> response = restTemplate.getForEntity("http://app-c.default.svc.cluster.local:6001/echo", String.class);
        if (response.getStatusCode().is2xxSuccessful()) {
            String body = response.getBody();
            return body;
        } else {
            return "request error";
        }
    }
}
```

app-c code
```java
package org.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
public class ProviderApplication {
    public static void main(String[] args) {
        SpringApplication.run(ProviderApplication.class, args);
    }
}

@RestController
class ProviderController {
    @GetMapping("/echo")
    public String echo() {
        return "Provider received msg V1";
    }
}
```

deploy the provider in the cluster with 2 different versions, 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: app-b
  labels:
    app: app-b
    service: app-b
spec:
  ports:
  - port: 6002
    name: http
  selector:
    app: app-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  labels:
    app: app-b
spec:
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: consumer
        image: swr.cn-north-4.myhuaweicloud.com/hwstaff_pub_torontodsdelab/consumer:v7
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 6002
---
apiVersion: v1
kind: Service
metadata:
  name: app-c
  labels:
    app: app-c
    service: app-c
spec:
  ports:
  - port: 6001
    name: http
  selector:
    app: app-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-c
  labels:
    app: app-c
spec:
  selector:
    matchLabels:
      app: app-c
  template:
    metadata:
      labels:
        app: app-c
    spec:
      containers:
      - name: app-c
        image: swr.cn-north-4.myhuaweicloud.com/hwstaff_pub_torontodsdelab/provider:v2
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 6001
```

apply the following virtualservice to redirect the request from provider to provider-v1

virtual service:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: route
spec:
  hosts:
  - app-c.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: app-c.default.svc.cluster.local
```

send request to app-b:
```bash
$ kubectl exec -it netutils -- curl http://app-c.default.svc.cluster.local:6001/echo
```

**Anything else we need to know?**:

**Environment**:
- Kmesh version: Latest
- Ubuntu 22.04 with enhanced kernal
- CCE 1.27 with coreDNS plugin
- Istio 1.19
