### ISSUE TITLE
There are residuals left in the kmesh ads config after deleting the service

### ISSUE THREAD

**Issue by lec-bit** [kmesh-net/kmesh#440]
**What happened**:
When I applied a service and then deleted it, there were still some residual configurations left in the kmesh ADS CDS configuration
```
    "clusterConfigs":  [
      {
        "name":  "outbound|80||fortio-server.default.svc.cluster.local",
        "connectTimeout":  10,
        "lbPolicy":  "LEAST_REQUEST",
        "loadAssignment":  {
          "clusterName":  "outbound|80||fortio-server.default.svc.cluster.local"
        },
        "circuitBreakers":  {
          "maxConnections":  4294967295,
          "maxPendingRequests":  4294967295,
          "maxRequests":  4294967295,
          "maxRetries":  4294967295
        }
      },

```
**What you expected to happen**:
there should be no residual configurations
**How to reproduce it (as minimally and precisely as possible)**:
1. ads mode : helm install kmesh ./deploy/helm -n kmesh-system --create-namespace
2. kubectl apply -f service.yaml
3. kubectl delete -f service.yaml
4. curl localhost:15200/debug/config_dump/ads
5. check clusterConfigs

service.yaml:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fortio-server
  name: fortio-server
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: fortio-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortio-server
  template:
    metadata:
      labels:
        app: fortio-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: ambient-worker
      containers:
        - image: fortio/fortio
          imagePullPolicy: IfNotPresent
          name: fortio-server
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
```

**Anything else we need to know?**:

**Environment**:
- Kmesh version: main
- Others:
