### ISSUE TITLE
Problem about circuitbreaker proto

### ISSUE THREAD

**Issue by Okabe-Rintarou-0** [kmesh-net/kmesh#478]
**Please provide an in-depth description of the question you have**:
Here's an example of circuitbreakers:
```yaml
  clusters:
  - name: example_cluster
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    circuit_breakers:
      thresholds:
      - priority: DEFAULT
        max_connections: 1000
        max_pending_requests: 100
        max_requests: 100
        max_retries: 3
      - priority: HIGH
        max_connections: 2000
        max_pending_requests: 200
        max_requests: 200
        max_retries: 5
```

The circuit breakers should be an array with 2 elements. But at present we only pick the first one:
https://github.com/kmesh-net/kmesh/blob/bb1990048f1a58fd1a253b2bcbdf1ad5df287a1b/pkg/controller/ads/cache.go#L149-L167

**What do you think about this question?**:

**Environment**:
- Kmesh version: current main branch
- Others:
