### ISSUE TITLE
support /retest command for failed github workflow checks

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#699]
We use prow bot to label and trigger github activities
https://github.com/kmesh-net/test-infra/blob/main/prow/plugins.yaml

But now when github ci check failed, it is not possible to trigger retest without pushing a new commit. Thankfully prow bot seems to support retest github workflows.

```
- *January 11, 2022* Trigger plugin can now trigger failed github jobs.
    The feature needs to be enabled in the `triggers` section of the `plugin.yaml` config and can be specified per trigger as follows:

    ```yaml
    triggers:
    - repos:
      - org/repo
      - org2
      trigger_github_workflows: true
    ```
```

I would like to add that function.  If that is not possible, we can also use github action like https://github.com/marketplace/actions/github-pull-request-retest
