### ISSUE TITLE
Headless service support

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#816]
**What would you like to be added**:

We need to think about how to support headless service in kmesh. Need a proposal, of course.

As headless service has no cluster ip, but has associated endpoints. Dns resolve of a headless service can randomly return an endpoint ip. 

And there is another special headless service without selectors external name service: https://kubernetes.io/docs/concepts/services-networking/service/#without-selectors.  Istio has changed the behavior about externalname service. 

**Why is this needed**:

**Comment by LiZhenCheng9527** [comment]
## background

Kmesh now supports headless services. But there are some problems to discuss in Kmesh monitoring.
Kmesh monitoring now uses the target Port in `workload.Services` to determine the `destination_service` in the metric.
https://github.com/kmesh-net/kmesh/blob/071bfd8759458323a733684ce32c3cd1d4807820/pkg/controller/telemetry/metric.go#L424-L449
And confused about whether kmesh can differentiate between traffic accessing a pod directly or through a Service.
So at this stage, kmesh monitoring is based on the assumption that all traffic is accessed through the Service.

## problem

However, a problem was encountered when support the headless Servic.
Configuration of the `spec.ports` field in the headless configuration doesn't really do anything.
For example:
```yaml
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 8080
  selector:
    app: httpbin
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
When `curl http://httpbin-headless:80` it still work.
And, if a workload.Service has both headless Service and Service, which metric should be updated on a single access?
