### ISSUE TITLE
Can't use traffic mirroring capabilities of Kmesh

### ISSUE THREAD

**Issue by noobwei** [kmesh-net/kmesh#823]
**What happened**:

Can't use traffic mirroring capabilities of Kmesh:

Completed the task of transferring all traffic to v1:
![image](https://github.com/user-attachments/assets/3915505a-bf1a-4403-88f3-d174f51a35c3)
Failed to the task of traffic mirroring:
![image](https://github.com/user-attachments/assets/94d306b8-a72a-493e-8e6e-af2085950ca8)

**What you expected to happen**:

Traffic from v1 should be mirrored to v2

**How to reproduce it (as minimally and precisely as possible)**:

1. https://istio.io/latest/docs/tasks/traffic-management/mirroring/#before-you-begin
2. As we worked in ambient mode, I deploied a waypoint pod for 'httpbin' service. Refer to https://kmesh.net/en/docs/userguide/install_waypoint/
3. When I refered to https://istio.io/latest/docs/tasks/traffic-management/mirroring/#creating-a-default-routing-policy, error happened as: `error: error parsing STDIN: error converting YAML to JSON: yaml: line 6: did not find expected key`. So I post my yaml here.

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
    - httpbin
  http:
    - route:
        - destination:
            host: httpbin
            subset: v1
          weight: 100
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: httpbin
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
EOF
```

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
    - httpbin
  http:
    - route:
        - destination:
            host: httpbin
            subset: v1
          weight: 100
      mirror:
        host: httpbin
        subset: v2
      mirrorPercentage:
        value: 100.0
EOF
```
4.  Then test refer to the istio website
```
kubectl exec deploy/sleep -c sleep -- curl -sS http://httpbin:8000/headers
kubectl logs deploy/httpbin-v1 -c httpbin
kubectl logs deploy/httpbin-v2 -c httpbin
```

**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:
