### ISSUE TITLE
manage applications by adding a label does't work in new version kubectl and istioctl.

### ISSUE THREAD

**Issue by derekwin** [kmesh-net/kmesh#910]
ENV:
```
os version: euler23，
kernel: 6.4.0-10.1.0.20.oe2309.x86_64
istioctl: 1.23.1
kubectl version: 1.31.0
build cluster by kind 0.19
```
after installing istio(ambient mode) and kmesh successfully.

I try to label the namespace by `kubectl label namespace default istio.io/dataplane-mode=Kmesh`

result: `namespace/default labeled`

then, I start a service with one pod.
```
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
    service: helloworld
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
  trafficDistribution: PreferClose
```
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-region1.zone1-1
  labels:
    app: helloworld
    version: region1.zone1-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: region1.zone1-1 
  template:
    metadata:
      labels:
        app: helloworld
        version: region1.zone1-1
    spec:
      containers:
      - name: helloworld
        env:
        - name: SERVICE_VERSION
          value: region1.zone1-1
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      nodeSelector:
        kubernetes.io/hostname: c1-worker 
```

result:
```
kubectl get pod
NAME                                          READY   STATUS    RESTARTS   AGE
helloworld-region1.zone1-1-7df698b8c8-6q5gb   2/2     Running   0          9m38s
```

bug is:
```
kubectl describe po helloworld-region1.zone1-1-7df698b8c8-qgmf9 | grep Annotations
Annotations:      istio.io/rev: default
```
it's different from the [kmesh document](https://kmesh.net/en/docs/setup/quickstart/):
```
kubectl describe po xxxx| grep Annotations
Annotations:      kmesh.net/redirection: enabled
```

And I notice that traffic can't be managed by kmesh at the same time. (kmesh userspace works, but bpf prog doesn't work),
this bug is happend after i update my istioctl to 1.23.1 and kubectl (and kindest node) to 1.31.1.
