### ISSUE TITLE
Memory scaling issue with large number of services

### ISSUE THREAD

**Issue by tmodak27** [kmesh-net/kmesh#945]
Motivation:
Our business case needs memory to scale as number of services increases, especially in scenarios where the scale is very high.

**1. What we did**

Environment Details:

- Kubernetes: 1.28 (CCE)
- Istio: 1.19
- Kmesh version: release 0.5
- CPU: 8
- Memory: 16 Gib
- Tool for measuring memory: [Inspektor-Gadget](https://www.inspektor-gadget.io/)

We started scaling up in batches of 500 services using the below yaml file and command.

- yaml file
```
# svc.yaml
kind: Service
apiVersion: v1
metadata:
  name: foo-service
  labels:
    foo: bar
spec:
  clusterIP: None
  selector:
    app: foo
  ports:
  - port: 5678

```

- scaling up command
```
$ for i in $(seq 1 500); do sed "s/foo-service/foo-service-0-$(date +%s-%N)/g" svc.yaml | kubectl apply -f -; done
```

After every 500 services, we measured the memory consumption using [inspektor gadget](https://www.inspektor-gadget.io/). The command used to measure the memory is `kubectl gadget top ebpf --sort comm`

**2. What we observed**: 

The total memory usage of the kmesh bpf map remained constant, even though the number of entries in the bpf map increased (table below).

<img width="500" alt="image" src="https://github.com/user-attachments/assets/ee7fade5-93b5-4657-8370-5ee408b70c9f">

The detailed table that has the memory consumption is attached below. Please refer to the column MAPMEMORY in the table.
[memory_hce.txt](https://github.com/user-attachments/files/17345717/memory_hce.txt)

**3. Why we think this is a problem**

Our business case requires memory usage to scale as we deploy more services, instead of remaining fixed.
