### ISSUE TITLE
Create a repo for DNS CoreDNS plugin to enable Kmesh DNS Capture feature

### ISSUE THREAD

**Issue by PerforMance308** [kmesh-net/kmesh#966]
**1. Background information:**

As discussed with @nlgwcy @hzxuzhonghu , we decide to implement the DNS capture feature based on CoreDNS plugin.

![image](https://github.com/user-attachments/assets/a49eba4d-bb94-423b-a04b-6df08ad1bfd4)

**2. What would you like to be added**:

I have finished implementing this coreDNS plugin and @nlgwcy @hzxuzhonghu if can help creating a repo under `kmesh-net` for it.

**3. Why is this needed**:
This fearue helped Kmesh to resolve user-defined domains that cannot be resolved by coredns. For example:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
spec:
  hosts:
  - app.DEFAULT_GROUP.public.nacos
  addresses:
  - 17.17.17.17
  - 9.9.9.9
  resolution: STATIC
  endpoints:
```

Without this feature, if we do `curl app.DEFAULT_GROUP.public.nacos` will return` couldn't resolve domain error`
